title: Daizan Soriano
description: Un blog sobre práctica, vida y dharma
url: https://daizansoriano.com
baseurl: ""
lang: es
image: /assets/logo.png
markdown: kramdown
kramdown:
  input: GFM
permalink: /:title/
collections:
  podcast:
    output: true
    permalink: /:title/
  xinxinming:
    output: true
    permalink: /xin-xin-ming/:name/
  xinxinming_versos:
    output: true
    permalink: /xin-xin-ming/verso/:name/
podcast_meta:
  author: Daizan Soriano
  owner_name: Daizan Soriano
  owner_email: daizansoriano@caminomedio.org
  web_image: /assets/daizan.jpg
  image: /assets/podcast-cover-3000.jpg
  category: Religion & Spirituality
  subcategory: Religion
  explicit: false
xinxinming_meta:
  buy_url: "https://amzn.to/4l8X8iv"
  buy_label: "Comprar en Amazon"
  cover_image: "/assets/images/2025/portada_xinxinming.png"
  cover_alt: "Portada del libro Xin Xin Ming de Daizan Soriano"
timezone: UTC
pwa_sw_version: v0.5.3
goatcounter:
  code: "daizansoriano"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
sass:
  style: compressed
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: ""
  - scope:
      path: ""
      type: podcast
    values:
      layout: podcast
      image: /assets/logo.png
  - scope:
      path: ""
      type: xinxinming
    values:
      layout: xxm-section
  - scope:
      path: ""
      type: xinxinming_versos
    values:
      layout: xxm-verse
