title: Daizan Soriano
description: Un blog sobre práctica, vida y dharma
url: https://daizansoriano.com
baseurl: ""
lang: es
markdown: kramdown
kramdown:
  input: GFM
permalink: /:title/
collections:
  podcast:
    output: true
    permalink: /:title/
podcast:
  author: Daizan Soriano
  owner_name: Daizan Soriano
  owner_email: daizansoriano@caminomedio.org
  image: /assets/daizan.jpg
  category: Religion & Spirituality
  subcategory: Religion
  explicit: false
timezone: UTC
pwa_sw_version: v0.3.1
goatcounter:
  code: "daizansoriano"
plugins:
  - jekyll-feed
sass:
  style: compressed
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: ""
  - scope:
      path: ""
      type: podcast
    values:
      layout: podcast
      image: /assets/logo.png
